config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "products#index"
  resources :products do
    member do
      post :add_to_cart
    end
  end
  resources :orders do
    collection do
      get :get_line_items
    end
    member do
      post :remove_item
      post :edit_item
      post :checkout
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  delegate :user, to: :order
  delegate :uid, to: :product

  def set_total_price(set_pcs=nil)
    set_pcs ||= self.pcs
    update!(total_price: set_pcs * product.price, pcs: set_pcs)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  after_create do
    default_name
  end

  enum status: {
    cart:     1,  # 購物車
    ready:    2,  # 新成立訂單
    shipped:  3,  # 已出貨
    returned: 4,  # 已退貨
  }
  enum financial_status: {
    not_paid:        1,
    paid:            2,
    pending_refund:  3,
    refunded:        4,
  }

  def default_name
    self.name = '#' + sprintf("%05d", id)
    self.save!
  end

  def add_to_cart(product, pcs)
    raise "數量需大於 1 !" if pcs <= 0
    with_lock do
      Order.transaction do
        item = line_items.where(product_id: product.id).last.presence
        if item.nil?
          line_items.create!(product_id: product.id, pcs: pcs, total_price: product.price * pcs)
        else
          item.pcs += pcs
          item.total_price = product.price * item.pcs
          item.save!
        end
        set_total_price
      end
    end
  end

  def set_total_price
    if line_items.exists?
      update!(price: line_items.sum(&:total_price))
    end
  end

  def items
    items_array = line_items.includes(:product).map do |item|
      {
        product_name: item.product.name,
        product_id: item.product.id,
        pcs: item.pcs,
        pcs_price: item.product.price,
        total_price: item.total_price
      }
    end
    # items_array << { order_total_price:
  end

end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create do
    default_cart
  end

  def default_cart
    orders.create unless orders.cart.exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  private

  def render_success(data = {})
    render json: data, status: 200
  end

  def render_failure(msg)
    render json: { message: msg }, status: 400
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:checkout, :edit_item, :remove_item, :edit, :show, :update, :destroy]

  def get_line_items
    if params[:order_id].present?
      order = current_user.orders.find(params[:order_id])
    else
      order = current_user.orders.cart.last || current_user.default_cart
    end
    item_array = order.items
    render json: { success: true, order_id: order.id, order_name: order.name, items: item_array, total_price: order.price }
  rescue => e
    render_failure(e.message)
  end

  def remove_item
    item = @order.line_items.where(product_id: params[:product_id]).last
    item.destroy!
    @order.set_total_price
    item_array = @order.items
    data = { order_id: @order.id, items: item_array, total_price: @order.price }
    render_success(data)
  rescue => e
    render_failure(e.message)
  end

  def edit_item
    pcs = params[:pcs].to_i
    raise "數量不能小於 0" if pcs < 0
    item = @order.line_items.where(product_id: params[:product_id]).last
    if pcs == 0
      item.destroy!
    else
      item.set_total_price(pcs)
    end
    @order.set_total_price
    item_array = @order.items
    data = { order_id: @order.id, items: item_array, total_price: @order.price }
    render_success(data)
  rescue => e
    render_failure(e.message)
  end

  def checkout
    @order.confirm_at = Time.current
    @order.save!
    @order.ready!
    # render_success({order_id: @order.id})
    redirect_to order_path(@order)
  end

  def index
    @orders = current_user.orders.where.not(status: 'cart')
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @products = Product.all
    # render json: { success: true, order: @order.as_json(include: [{ line_items: { include: :product } }]) }
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = current_user.orders.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {})
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :add_to_cart]

  def add_to_cart
    order = current_user.orders.cart.last || current_user.default_cart
    order.add_to_cart(@product, params[:pcs].to_i)
    render json: { success: true, order: order.as_json(include: [{ line_items: { include: :product } }]) }

    # render status: 200
  rescue => e
    render json: { message: e.message }, status: 400
  end
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    # render json: { product: @products.as_json}
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :uid, :stock, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/common/_footer.html.erb
<footer>

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns here to organize your footer content.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

          <!-- Links -->
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">

          <!-- Links -->
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>

        </div>
        <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>

app/views/common/_header.html.erb
<div class="logo_products">
  <div class="container">
    <div class="w3ls_logo_products_left1">
      <ul class="phone_email">
        <li><i aria-hidden="true" class="fa fa-phone">
            <order>online or call us : (+0123) 234 567</order>
          </i></li>
      </ul>
    </div>
    <div class="w3ls_logo_products_left">
      <h1><a href="/"> super Market</a></h1>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

<div class="navigation-agileits">
  <nav class="navbar navbar-expand-lg navbar-light"><a class="navbar-brand" href="#" style="color: #fff">Ian's Shop</a><button
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
      data-target="#navbarNavDropdown" data-toggle="collapse" type="button"><span class="navbar-toggler-icon" style="color: #fff"></span></button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <%# <li class="nav-item"><a class="nav-link" href="/" style="color: #fff">Home<span class="sr-only" current=""></span></a></li> %>
        <li class="nav-item"><a class="nav-link" href="/products" style="color: #fff"> Shopping</a></li>
        <li class="nav-item"><a class="nav-link" href="/orders" style="color: #fff"> My Orders</a></li>
        <%# <div class="agile-login"> %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <li class="nav-item"><%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "nav-link", style: "color: #fff;padding-left: 10") %> </li>
          <li class="nav-item"><%= link_to('Change Password', edit_registration_path(:user), class: "nav-link", style: "color: #fff") %></li>
          <li class="nav-item">
            <div class="product_list_header">
              <button class="w3view-cart" name="submit" type="submit" value="">
                <i aria-hidden="true" class="fa fa-cart-arrow-down" data-target="#cartModal" data-toggle="modal"></i>
              </button>
            </div>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to('Create Account', new_registration_path(:user), class: "nav-link", style: "color: #fff") %> </li>
          <li class="nav-item"><%= link_to('Login', new_session_path(:user), class: "nav-link", style: "color: #fff") %> </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <meta content="width=device-width, initial-scale=1" name="viewport" />
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
  <link href="//fonts.googleapis.com/css?family=Raleway:400,100,100italic,200,200italic,300,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic" rel="stylesheet" type="text/css" />
  <link href="//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic" rel="stylesheet" type="text/css" />
  <head>
    <title>GoodlifeShoppingCartDesign</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= render "common/header" %>
  </head>

  <body>

    <p class=”notice”><%= notice %></p>
    <p class=”alert”><%= alert %></p>

    <%= yield %>
    <%# <%= render "common/footer" %>
  </body>
</html>

app/views/orders/_form.html.slim
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      h2 = "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      ul
        - @order.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/orders/edit.html.slim
h1 Editing order

== render 'form'

=> link_to 'Show', @order
'|
=< link_to 'Back', orders_path

app/views/orders/index.html.slim
h1 Listing orders

table.table.table-striped
  thead
    tr
      th(scope="col") Order Number
      th(scope="col") Confirm At
      th(scope="col") Total Price
      th(scope="col")
      th(scope="col")
  tbody
    - @orders.each do |order|
      tr
        td(scope="row") = order.name
        td(scope="row") = order.confirm_at.strftime('%F %T')
        td(scope="row") = order.price
        td(scope="row") = link_to 'Show Detail', order
        / (scope="row")td = link_to 'Edit', edit_order_path(order)
        td(scope="row") = link_to 'Destroy', order, data: { confirm: 'Are you sure?' }, method: :delete

br

/ = link_to 'New Order', new_order_path

app/views/orders/new.html.slim
h1 New order

== render 'form'

= link_to 'Back', orders_path

app/views/orders/show.html.slim
= javascript_pack_tag 'order'
#orderVue
/ #cart
/ p#notice = notice


/ => link_to 'Edit', edit_order_path(@order)
/ '|
=< link_to 'Back To Order List', orders_path

app/views/products/_form.html.slim
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :uid
    = f.text_field :uid
  .field
    = f.label :stock
    = f.number_field :stock
  .field
    = f.label :price
    = f.number_field :price
  .actions = f.submit

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

=> link_to 'Show', @product
'|
=< link_to 'Back', products_path

app/views/products/index.html.slim
= javascript_pack_tag 'cart'

#cart

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice = notice

p
  strong Name:
  = @product.name
p
  strong Uid:
  = @product.uid
p
  strong Stock:
  = @product.stock
p
  strong Price:
  = @product.price

=> link_to 'Edit', edit_product_path(@product)
'|
=< link_to 'Back', products_path
javascript:
  console.log('test111')